services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth-password
      POSTGRES_DB: auth
    ports:
      - "5050:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: